var first_name="Pralove";
var last_name="Shah";
f_name.concat(l_name);
var a = 10;
var b = 5;
var add = a + b;
console.log(add);
var subtract = a - b;
console.log(subtract);
var divide = a / b;
console.log(divide);
var multiply = a * b;
console.log(multiply);